pipeline{
	agent any

	stages{
	    stage("Build"){
		steps{
			echo "Building"
		    }
		}

	    stage("run"){
		steps{
			echo "running"
		    }
		}
	    stage("test"){
		 steps{
		    echo "Testing"
		}
	    }		
	}
}
